Sheep Shearer Rewrite
Zoinkwiz/quest-helper pull request #1156
Opened 2023-06-13 23:05 UTC by Obasill

More of a walk through and slightly more elegant solution. With steps on how to get the wool, turn wool into balls of wool, and then turn in. It's not perfect but I added things to catch edge cases such as opening the helper mid-quest progress.

2023-07-01 17:04 UTC, Zoinkwiz requested changes
Currently this is a bit problematic for if a player has a semi-full inventory, as the quest won't progress until you have all the wool. Also, if a player hands in partial quantities it'll cause the helper to close as steps don't exist for the intermediate steps.

2024-03-02 12:14 UTC, pajlada requested changes
Additionally, when going for my last sheep to shear, quest helper didn't prompt me to spin them into balls of wool even though I should have at this point
![image](https://github.com/Zoinkwiz/quest-helper/assets/962989/633ebfd2-0c10-4814-bfc8-c29f7bddf3c2)

Not fully related to this PR, but I noticed the Sheep don't get highlighted again after growing their wool back

2024-03-02 12:14 UTC, pajlada commented on src/main/java/com/questhelper/helpers/quests/sheepshearer/SheepShearer.java
> +			"Talk Fred the Farmer north of Lumbridge to start the quest. Bring 20 balls of wool to autocomplete the quest.");
```suggestion
			"Talk to Fred the Farmer north of Lumbridge to start the quest. Bring 20 balls of wool to autocomplete the quest.");
```

2024-03-02 12:14 UTC, pajlada commented on src/main/java/com/questhelper/helpers/quests/sheepshearer/SheepShearer.java
> +		shears.setTooltip("if you plan on collecting wool yourself");
nit: capitalization
```suggestion
		shears.setTooltip("If you plan on collecting wool yourself");
```

2024-03-10 12:24 UTC, merged