Project Rebalance Achievement Diary Agility Shortcut Changes
Zoinkwiz/quest-helper pull request #1642
Opened 2024-07-15 22:53 UTC by shookietea

https://secure.runescape.com/m=news/project-rebalance-skilling--poll-81-mta-changes?oldschool=1

Achievement Diary requirements were removed from some agility shortcuts. This PR brings the achievement diaries up to date.

2024-07-21 12:45 UTC, pajlada requested changes
Some nits + some additions you can add, if you want to, while you're in these files

Missing reward at the bottom of Desert Hard diary: `Increased experience on the Pollnivneach Rooftop Course`
Missing reward at the bottom of Fremennik Hard: `Increased experience on the Rellekka Rooftop Course`
Missing reward at the bottom of Karamja Medium: `10% additional Agility experience earned from all obstacles in the Brimhaven Agility Arena when wearing Karamja gloves`

2024-07-21 12:45 UTC, pajlada commented on src/main/java/com/questhelper/helpers/achievementdiaries/desert/DesertHard.java
> +			new UnlockReward("Access to the shortcut just north of the Shantay Pass, requiring 70 Agility"),
This reward was removed outright, so the entry should just be removed

2024-07-21 12:45 UTC, pajlada commented on src/main/java/com/questhelper/helpers/achievementdiaries/karamja/KaramjaMedium.java
> +			new UnlockReward("10% increased Agility experience earned from Brimhaven Agility Arena"));
```suggestion
			new UnlockReward("10% increased Agility experience earned from Brimhaven Agility Arena when wearing Karamja gloves"));
```

2024-07-22 03:15 UTC, shookietea commented
Happy to make those changes! For the Rellekka and Pollnivneach courses, is it bonus experience for completing laps, or each obstacle?

https://oldschool.runescape.wiki/w/Fremennik_Diary#Rewards_3 makes me wonder if I should be more precise with the wording, but I unfortunately cannot test these

2024-07-22 06:23 UTC, pajlada commented
> https://oldschool.runescape.wiki/w/Fremennik_Diary#Rewards_3 makes me wonder if I should be more precise with the wording, but I unfortunately cannot test these

If you use the same phrasing the wiki team does, you should be fine

2024-07-27 22:26 UTC, shookietea commented
> > https://oldschool.runescape.wiki/w/Fremennik_Diary#Rewards_3 makes me wonder if I should be more precise with the wording, but I unfortunately cannot test these
> 
> If you use the same phrasing the wiki team does, you should be fine

This is updated now, thanks!

2024-07-28 09:32 UTC, pajlada approved these changes

2024-07-30 11:35 UTC, merged