Tribal totem
Zoinkwiz/quest-helper pull request #65
Opened 2020-11-14 14:10 UTC by twinkle-is-dum

I should probably rename CombinationLockStep to PuzzleStep but the rest should be good. I also need to see if checkstyle is good. Just opening the PR for now (:

2020-11-14 16:18 UTC, Zoinkwiz requested changes
Couple comments otherwise looks good!

2020-11-14 16:18 UTC, Zoinkwiz commented on src/main/java/com/questhelper/quests/tribaltotem/CombinationLockStep.java
> +        int Id = current.charAt(0) < target.charAt(0) ? arrowRightId : arrowLeftId;
You could make this choose to go backwards/forwards considering proximity in both directions by doing something like the following:

```
char current = widget.getText().charAt(0);
int currentPos = (int)current - (int)'A';
int id = Math.floorMod(currentPos - target, 26) < Math.floorMod(target - currentPos, 26) ? arrowRightId : arrowLeftId;
```

2020-11-14 16:18 UTC, Zoinkwiz commented on src/main/java/com/questhelper/quests/tribaltotem/TribalTotem.java
> +        houseFirstFloor = new Zone(new WorldPoint(2630, 3319, 1), new WorldPoint(2638, 3323, 1));
The first floor needs to extend a tile further south and east to capture the entire first floor.

2020-11-15 10:20 UTC, twinkle-is-dum commented on src/main/java/com/questhelper/quests/tribaltotem/TribalTotem.java
> +        talkToEmployee = new NpcStep(this, NpcID.GPDT_EMPLOYEE, new WorldPoint(2647, 3272, 0), "Talk to a nearby GPDT employee.");
Did not know this was possible, added

2020-11-15 19:41 UTC, Zoinkwiz approved these changes
LGTM, thanks!

2020-11-15 19:41 UTC, merged